#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"
                              
$L "   ____                                                          __  __               _  ";
$L "  / ___|  _   _    __ _   _ __     ___     __ _    ___   _ __   |  \/  |   ___     __| | ";
$L " | |     | | | |  / _` | | '_ \   / _ \   / _` |  / _ \ | '_ \  | |\/| |  / _ \   / _` | ";
$L " | |___  | |_| | | (_| | | | | | | (_) | | (_| | |  __/ | | | | | |  | | | (_) | | (_| | ";
$L "  \____|  \__, |  \__,_| |_| |_|  \___/   \__, |  \___| |_| |_| |_|  |_|  \___/   \__,_| ";
$L "          |___/                           |___/                                          ";

$L "Welcome to Android `getprop ro.build.version.release` / CyanogenMod-`getprop ro.cm.version`";
