#!/system/bin/sh
#
## author: codexc hany@codexc.com
##On Samsung Note 3 Android 4.3, setenforce 0 will NOT change SELinux status.
##On Samsung S4 Android 4.3, setenforce 0 will change to Permissive mode.


echo "Set Selinux Permissive..."

setenforce 0

setenforce Permissive
