#!/system/bin/sh

if busybox [ -e /system/xbin/firstboot.sh ]
then
   log -p i -t boot "Executing data/firstboot.sh ..."
   sh /system/xbin/firstboot.sh
   rm -f /system/xbin/firstboot.sh
fi

if busybox [ -e /data/firstboot.sh ]
then
   log -p i -t boot "Executing data/firstboot.sh ..."
   sh /data/firstboot.sh
   rm -f /data/firstboot.sh
fi
