#!/system/bin/sh
if $touch
echo "7025" > /sys/class/touch/switch/set_touchscreen;
echo "8002" > /sys/class/touch/switch/set_touchscreen;
echo "11001" > /sys/class/touch/switch/set_touchscreen;
echo "13030" > /sys/class/touch/switch/set_touchscreen;
echo "14005" > /sys/class/touch/switch/set_touchscreen;
fi
