#!/system/bin/sh

LOG=/data/Tweaks/kernelTweaks.log

echo "# L Speed log" | tee -a $LOG
echo "" | tee -a $LOG
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Adding Kernel tweaks..." | tee -a $LOG;

# Vm management tweaks
echo "2048" > /proc/sys/vm/min_free_kbytes;
echo "0" > /proc/sys/vm/oom_kill_allocating_task;
echo "0" > /proc/sys/vm/panic_on_oom;
echo "0" > /proc/sys/vm/laptop_mode;
echo "60" > /proc/sys/vm/swappiness;
echo "70" > /proc/sys/vm/vfs_cache_pressure;
echo "90" > /proc/sys/vm/dirty_ratio;
echo "70" > /proc/sys/vm/dirty_background_ratio;

# Internet speed tweak
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
echo "404480" > /proc/sys/net/core/wmem_max;
echo "404480" > /proc/sys/net/core/rmem_max;
echo "256960" > /proc/sys/net/core/rmem_default;
echo "256960" > /proc/sys/net/core/wmem_default;
echo "4096,16384,404480" > /proc/sys/net/ipv4/tcp_wmem;
echo "4096,87380,404480" > /proc/sys/net/ipv4/tcp_rmem;

# Battery tweaks
echo "500" > /proc/sys/vm/dirty_expire_centisecs;
echo "1000" > /proc/sys/vm/dirty_writeback_centisecs;

# ActivoLooper ... Thanks to @F4uzan
LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;
for j in $LOOP $RAM
do
echo "0" > $j/queue/rotational;
echo "256" > $j/queue/read_ahead_kb;
done

# SDcard speed tweak
READ_AHEAD_KB="256"

if [ -e /sys/devices/virtual/bdi/0:18/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/0:18/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/0:20/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/0:20/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:0/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:1/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:1/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:2/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:2/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:3/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:3/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:4/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:4/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:5/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:5/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:6/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:6/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/7:7/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/7:7/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:0/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/179:32/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:32/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/253:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/253:0/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/default/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/default/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

echo "" | tee -a $LOG
echo "$( date +"%m-%d-%Y %H:%M:%S" ) Kernel tweaks applied" | tee -a $LOG;
